# Generated by Django 2.0.3 on 2018-03-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='researchdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('article_title', models.CharField(default='none', max_length=30)),
                ('article_author_name', models.CharField(default='none', max_length=30)),
                ('article_year', models.DateField(null=True)),
                ('article_keywords', models.CharField(default='none', max_length=30)),
            ],
        ),
    ]
