# Generated by Django 2.0.3 on 2018-04-03 04:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_researchdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_author_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='article_entity',
            fields=[
                ('article_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('article_title', models.CharField(default='none', max_length=100)),
                ('article_year', models.CharField(default='none', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='article_key_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.article_entity')),
            ],
        ),
        migrations.CreateModel(
            name='author_entity',
            fields=[
                ('author_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='none', max_length=100)),
                ('last_name', models.CharField(default='none', max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='key_entity',
            fields=[
                ('key_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='article_key_rel',
            name='key_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.key_entity'),
        ),
        migrations.AddField(
            model_name='article_author_rel',
            name='article_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.article_entity'),
        ),
        migrations.AddField(
            model_name='article_author_rel',
            name='author_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.author_entity'),
        ),
    ]
