# Generated by Django 2.0.3 on 2018-04-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180403_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_entity',
            name='author_fk',
        ),
        migrations.RemoveField(
            model_name='article_entity',
            name='key_fk',
        ),
        migrations.AddField(
            model_name='article_entity',
            name='authors',
            field=models.ManyToManyField(default='none', to='webapp.author_entity'),
        ),
        migrations.AddField(
            model_name='article_entity',
            name='keywords',
            field=models.ManyToManyField(default='none', to='webapp.key_entity'),
        ),
    ]
