# Generated by Django 2.0.3 on 2018-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180403_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_entity',
            name='authors',
        ),
        migrations.AlterField(
            model_name='article_entity',
            name='article_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='article_entity',
            name='article_year',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='article_entity',
            name='keywords',
            field=models.ManyToManyField(to='webapp.key_entity'),
        ),
        migrations.AlterField(
            model_name='key_entity',
            name='key_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='key_entity',
            name='keyword',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
