# Generated by Django 2.0.3 on 2018-04-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180403_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key_entity',
            name='keyword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
