# Generated by Django 2.0.3 on 2018-04-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20180403_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_entity',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='key_entity',
        ),
    ]
