# Generated by Django 2.0.3 on 2018-04-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20180403_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='key_entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
