# Generated by Django 2.0.3 on 2018-04-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_key_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_entity',
            name='keywords',
            field=models.ManyToManyField(to='webapp.key_entity'),
        ),
    ]
