# Generated by Django 2.0.3 on 2018-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_article_entity_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_entity',
            name='keywords',
        ),
        migrations.AddField(
            model_name='article_entity',
            name='authors',
            field=models.ManyToManyField(default=None, to='webapp.author_entity'),
        ),
        migrations.DeleteModel(
            name='key_entity',
        ),
    ]
