# Generated by Django 2.0.3 on 2018-04-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20180403_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='key_entity',
            fields=[
                ('key_id', models.UUIDField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article_entity',
            name='keywords',
            field=models.ManyToManyField(default=None, to='webapp.key_entity'),
        ),
    ]
