# Generated by Django 2.0.3 on 2018-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20180403_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='none', max_length=30)),
                ('author', models.CharField(default='none', max_length=30)),
                ('description', models.CharField(default='none', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article_entity',
            name='article_url',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='article_entity',
            name='article_title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
