# Generated by Django 2.0.3 on 2018-04-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20180414_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_entity',
            name='article_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
