# Generated by Django 2.0.3 on 2018-04-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20180414_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_entity',
            name='article_url',
        ),
    ]
