# Generated by Django 2.0.3 on 2018-04-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_remove_article_entity_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_entity',
            name='article_url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
