# Generated by Django 2.0.3 on 2018-04-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_article_entity_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_entity',
            name='article_url',
        ),
    ]
