# Generated by Django 2.0.3 on 2018-04-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_article_entity_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_entity',
            old_name='filename',
            new_name='link',
        ),
    ]
