# Generated by Django 2.0.3 on 2018-04-29 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20180428_0257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectsData',
        ),
        migrations.DeleteModel(
            name='researchdata',
        ),
        migrations.AlterModelOptions(
            name='author_entity',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='project_title',
            new_name='article_title',
        ),
    ]
