# Generated by Django 2.0.3 on 2018-04-29 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20180429_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article_title',
            new_name='project_title',
        ),
    ]
