# Generated by Django 2.0.3 on 2018-04-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20180429_0335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
