# Generated by Django 2.0.3 on 2018-04-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
